import { describe, it, expect } from 'vitest';
import { lineDiff, DiffOp } from '../../core/diff';

// v1.22.0 #97: pure line-level diff for the Schema diff Modal.
// Returns an array of per-line operations the UI can render as
// IDE-style +/- with red/green highlighting. The algorithm is the
// classic LCS dynamic-programming approach: O(n*m) time, O(n*m) space
// which is fine for schema files (typically < 200 lines, even after
// the v1.22.0 dynamic tag list expansion).
//
// The output preserves the *order* in which the user would see the
// changes: a "modified line" is emitted as one 'del' followed by one
// 'add' (left = removed, right = inserted), not as a paired operation.

describe('lineDiff (#97 Schema diff)', () => {
  it('returns all "eq" ops for two identical texts', () => {
    // Two identical inputs produce a "no change" diff — every line is
    // marked as 'eq'. The UI uses this to render both panes identically
    // (no red/green highlight), so the user sees the unchanged schema
    // context. An empty array would be a different semantic ("no input
    // at all") and would force the UI to special-case the no-change path.
    const text = 'line 1\nline 2\nline 3';
    expect(lineDiff(text, text)).toEqual<DiffOp[]>([
      { op: 'eq', line: 'line 1' },
      { op: 'eq', line: 'line 2' },
      { op: 'eq', line: 'line 3' },
    ]);
  });

  it('marks every line as "add" when old is empty', () => {
    const result = lineDiff('', 'a\nb\nc');
    expect(result).toEqual<DiffOp[]>([
      { op: 'add', line: 'a' },
      { op: 'add', line: 'b' },
      { op: 'add', line: 'c' },
    ]);
  });

  it('marks every line as "del" when new is empty', () => {
    const result = lineDiff('a\nb\nc', '');
    expect(result).toEqual<DiffOp[]>([
      { op: 'del', line: 'a' },
      { op: 'del', line: 'b' },
      { op: 'del', line: 'c' },
    ]);
  });

  it('flags a single added line in the middle (insert)', () => {
    // old: a / c
    // new: a / b / c
    const result = lineDiff('a\nc', 'a\nb\nc');
    expect(result).toEqual<DiffOp[]>([
      { op: 'eq',  line: 'a' },
      { op: 'add', line: 'b' },
      { op: 'eq',  line: 'c' },
    ]);
  });

  it('flags a single removed line in the middle (delete)', () => {
    const result = lineDiff('a\nb\nc', 'a\nc');
    expect(result).toEqual<DiffOp[]>([
      { op: 'eq',  line: 'a' },
      { op: 'del', line: 'b' },
      { op: 'eq',  line: 'c' },
    ]);
  });

  it('treats a changed line as one del + one add (no paired "mod" op)', () => {
    // old: foo
    // new: bar
    // The UI renders the del with a left red bar and the add with a
    // right green bar — two entries, not one.
    const result = lineDiff('foo', 'bar');
    expect(result).toEqual<DiffOp[]>([
      { op: 'del', line: 'foo' },
      { op: 'add', line: 'bar' },
    ]);
  });

  it('preserves common prefix and suffix as "eq" entries', () => {
    // Shared header, divergent body, shared footer.
    const oldText = '# Wiki Schema\n\n## Wiki Structure\n- entities/\n## End';
    const newText = '# Wiki Schema\n\n## Wiki Structure\n- entities/ (custom)\n## End';
    const result = lineDiff(oldText, newText);
    expect(result[0]).toEqual({ op: 'eq', line: '# Wiki Schema' });
    expect(result.at(-1)).toEqual({ op: 'eq', line: '## End' });
    // Body change is exactly one del + one add
    const bodyChanges = result.filter(r => r.op !== 'eq');
    expect(bodyChanges).toEqual<DiffOp[]>([
      { op: 'del', line: '- entities/' },
      { op: 'add', line: '- entities/ (custom)' },
    ]);
  });

  it('preserves CRLF / LF difference tolerance (lines split on \\n only)', () => {
    // Most vaults use \n; we don't try to be smart about \r\n — the schema
    // is generated by us, not pasted from a Windows editor.
    const oldText = 'a\nb';
    const newText = 'a\nb\nc';
    const result = lineDiff(oldText, newText);
    expect(result).toEqual<DiffOp[]>([
      { op: 'eq', line: 'a' },
      { op: 'eq', line: 'b' },
      { op: 'add', line: 'c' },
    ]);
  });

  it('handles empty lines without treating them as missing', () => {
    // Empty lines should appear as 'eq' on both sides — not get swallowed
    // by the trim() that some diff tools do.
    const result = lineDiff('a\n\nb', 'a\n\nb');
    expect(result).toEqual<DiffOp[]>([
      { op: 'eq', line: 'a' },
      { op: 'eq', line: '' },
      { op: 'eq', line: 'b' },
    ]);
  });

  it('schema change scenario: a single tag-list line replacement', () => {
    // Realistic #97 scenario: LLM rewrites one bullet in the Entity
    // Page Template from the hardcoded list to a custom one.
    const oldText = [
      '## Entity Page Template',
      '- `tags:` — entity subtype, MUST be one of: person, organization, project, product, event, place, other',
    ].join('\n');
    const newText = [
      '## Entity Page Template',
      '- `tags:` — entity subtype, MUST be one of: person, organization, Medical_Arzneimittel',
    ].join('\n');
    const result = lineDiff(oldText, newText);
    expect(result).toEqual<DiffOp[]>([
      { op: 'eq',  line: '## Entity Page Template' },
      { op: 'del', line: '- `tags:` — entity subtype, MUST be one of: person, organization, project, product, event, place, other' },
      { op: 'add', line: '- `tags:` — entity subtype, MUST be one of: person, organization, Medical_Arzneimittel' },
    ]);
  });
});
