// welcome-note-template.ts — Tier-B first-run Welcome note generator
//
// Pure function. Renders the full markdown body of the v1.23.0
// Welcome note (frontmatter + 4 sections + closing auto-generated
// marker). The caller passes vault candidates, LLM smoke-test result,
// and an i18n translator. No I/O.
//
// The Welcome note is the Tier-B onboarding artifact (per the
// v1.23.0 three-tier design, refined 2026-06-27). Tier A users
// don't get one; Tier C users don't get one either. This function
// assumes "create Welcome note" is the desired behavior — the caller
// has already decided via tier-detection.ts.
//
// Section structure:
//   1. Frontmatter (type: welcome, created: ISO date)
//   2. H1 title
//   3. ## Domains (user fills — one per line, becomes tag vocab)
//   4. ## Initial Source Suggestions (plugin pre-fills with vault
//      candidates sorted by size descending; user checks 2-3)
//   5. ## Wiki Scope (user fills — LLM ingest context)
//   6. ## Configuration Test (plugin auto-maintains — LLM smoke test)
//   7. Closing <!-- end auto-generated --> marker
//
// Why size-descending order: heuristic for the seed suggestion list.
// Bigger notes likely have more substantive content, so they're
// better candidates for "ingest first to give the link graph
// structure". This is intentionally simple — the user can rearrange.

export interface VaultCandidate {
  /** Vault-relative path. Becomes the wikilink target in the suggestion. */
  path: string;
  /** Page title or filename without extension. */
  title: string;
  /** File size in bytes. Used for sort order (largest first). */
  size: number;
}

export interface LlmConfigStatus {
  ok: boolean;
  provider?: string;
  model?: string;
  /** Set when ok=false. Human-readable reason (e.g. "API key not configured"). */
  error?: string;
}

export interface BuildWelcomeNoteArgs {
  candidates: VaultCandidate[];
  llmConfig: LlmConfigStatus;
  /** I18n translator. Should resolve keys like 'welcome.domains' to localized strings. */
  i18n: { t: (key: string) => string };
  /** ISO date for the frontmatter `created` field. */
  createdAt: string;
}

const CANDIDATE_LIMIT = 10;

export function buildWelcomeNote(args: BuildWelcomeNoteArgs): string {
  const { candidates, llmConfig, i18n, createdAt } = args;
  const t = i18n.t;

  const frontmatter = renderFrontmatter(createdAt);
  const title = t('welcome.title');
  const intro = t('welcome.intro');
  const domainsSection = renderDomainsSection(t);
  const candidatesSection = renderCandidatesSection(candidates, t);
  const scopeSection = renderScopeSection(t);
  const configSection = renderConfigSection(llmConfig, t);
  const closing = '<!-- end auto-generated -->';

  const parts = [
    frontmatter,
    `# ${title}`,
    intro,
    domainsSection,
    candidatesSection,
    scopeSection,
    configSection,
    closing,
  ];

  return parts.filter(p => p.length > 0).join('\n\n') + '\n';
}

function renderFrontmatter(createdAt: string): string {
  return [
    '---',
    'title: Wiki Founding Note',
    'type: welcome',
    `created: ${createdAt}`,
    '---',
  ].join('\n');
}

function renderDomainsSection(t: (k: string) => string): string {
  return [
    `## ${t('welcome.domains')}`,
    '',
    t('welcome.domains.description'),
    '',
    `- (your domain 1)`,
    `- (your domain 2)`,
    `- (your domain 3)`,
  ].join('\n');
}

function renderCandidatesSection(candidates: VaultCandidate[], t: (k: string) => string): string {
  const header = `## ${t('welcome.initial_source_suggestions')}`;
  const description = t('welcome.initial_source_suggestions.description');

  // Sort by size descending — bigger notes likely have more content.
  const sorted = [...candidates]
    .sort((a, b) => b.size - a.size)
    .slice(0, CANDIDATE_LIMIT);

  if (sorted.length === 0) {
    // Degenerate Tier B: vault claimed to have notes but candidate
    // list is empty. Show section header with instruction, no list.
    return [
      header,
      '',
      description,
    ].join('\n');
  }

  const list = sorted.map(c => `- [ ] [[${c.path}]] — ${c.title}`).join('\n');
  return [header, '', description, '', list].join('\n');
}

function renderScopeSection(t: (k: string) => string): string {
  return [
    `## ${t('welcome.wiki_scope')}`,
    '',
    t('welcome.wiki_scope.description'),
    '',
    '> (your wiki scope — 1-2 sentences)',
  ].join('\n');
}

function renderConfigSection(llmConfig: LlmConfigStatus, t: (k: string) => string): string {
  const header = `## ${t('welcome.configuration_test')}`;
  const openMarker = '<!-- auto-generated by plugin: do not edit -->';

  let body: string;
  if (llmConfig.ok) {
    const status = `✅ ${t('welcome.config_ok')}`;
    const provider = `${t('welcome.config_provider')}: ${llmConfig.provider ?? 'unknown'}`;
    const model = `${t('welcome.config_model')}: ${llmConfig.model ?? 'unknown'}`;
    body = [status, provider, model].join('\n');
  } else {
    const status = `⚠️ ${t('welcome.config_failed')}`;
    const error = `${t('welcome.config_error')}: ${llmConfig.error ?? 'unknown'}`;
    body = [status, error].join('\n');
  }

  return [header, '', openMarker, body, '<!-- end auto-generated -->'].join('\n');
}