// welcome-note-template.ts — First-run Welcome note generator (v1.23.0)
//
// Pure function. Renders the Welcome note body (English template) which
// the LLM then translates to the user's wiki language at write time
// (D8 design, see core/localize-welcome-note.ts).
//
// The v1.23.0 refactor simplifies the structure to two purposes only
// (decided 2026-06-28 after user feedback):
//
//   1. **Install verification** — the "Configuration Test" section.
//      If the user can read this note in their wiki language AND the
//      LLM Configuration is ✅ OK, the install is verified.
//
//   2. **Reading guide** — a multi-section explanation of how the
//      plugin works and what the wiki structure means. Pure read-only:
//      no editable form fields, no checkbox to tick, no domain
//      declarations. All "fill in here" affordances from earlier
//      designs were promises without consumers (no code path reads
//      the resulting content), so we removed them in favor of clarity.
//
// Removed in this refactor (vs v1):
//   - "Domains" section — no code consumed it; user feedback:
//     "user input is not necessary, just direct users to ingest".
//   - "Wiki Scope" section — same reason. Future ingest-context
//     wiring (read Welcome as LLM system prompt hint) deferred to
//     v1.24+ if there's real demand.
//   - "Initial Source Suggestions" section (with checkboxes) — the
//     checkboxes were dead code (no handler for "- [ ] [[path]]");
//     v1.23.0 ships the actual multi-file ingest command (see
//     #130) which makes the checkbox affordance obsolete.
//
// What this template DOES render:
//   - Frontmatter (type: welcome, created: ISO date, llm_config: machine-readable status)
//   - H1 title
//   - Intro paragraph
//   - "How to verify the install" — two green-lights check
//   - "How to use this plugin" — the 6 most-useful commands
//   - "What the wiki structure means" — entity / concept / source / Schema
//   - "Quick start" — 4-step first-time flow
//
// What this template does NOT render (v1.23.0 refactor):
//   - "Configuration Test" section with visible ✅/⚠ status, provider name,
//     model name, and HTML-comment markers. Reason: user feedback
//     2026-06-28 — visible status row breaks the reading flow and
//     "looks like debug output". LLM config state now lives in
//     frontmatter as `llm_config:` (machine-readable, hidden by default
//     in Obsidian's reading view). Install verification is the
//     responsibility of the plugin's own UI (Settings → Karpathy LLM
//     Wiki → LLM Provider → "Test Connection" button).
//
// D8 NOTE: All section headers and descriptions are English hardcoded
// here. Do NOT extract these into per-locale files. The LLM translator
// (localize-welcome-note.ts) will produce the localized version.
//
// LINE-BREAK NOTE: We use a separate string per visual line inside
// paragraphs (e.g. indented continuation text). The markdown source
// uses real newlines between them, but these are NORMAL newlines —
// Obsidian does NOT render a single trailing newline as a hard
// break, so the renderer auto-wraps to the viewport. This avoids the
// "premature hard-wrap" rendering bug introduced in the v1 draft.

export interface LlmConfigStatus {
  ok: boolean;
  provider?: string;
  model?: string;
  /** Set when ok=false. Human-readable reason (e.g. "API key not configured"). */
  error?: string;
}

export interface BuildWelcomeNoteArgs {
  llmConfig: LlmConfigStatus;
  /** ISO date for the frontmatter `created` field. */
  createdAt: string;
}

export function buildWelcomeNote(args: BuildWelcomeNoteArgs): string {
  const { llmConfig, createdAt } = args;

  const frontmatter = renderFrontmatter(llmConfig, createdAt);
  const title = 'Welcome to your LLM-Wiki';
  const intro = [
    'This note is auto-generated by the Karpathy LLM Wiki plugin on first run. You don\'t need to edit it — read once, then start ingesting.',
  ].join('\n');
  const verifySection = renderVerifySection(llmConfig);
  const howToUseSection = renderHowToUseSection();
  const structureSection = renderStructureSection();
  const quickStartSection = renderQuickStartSection();

  const parts = [
    frontmatter,
    `# ${title}`,
    intro,
    verifySection,
    howToUseSection,
    structureSection,
    quickStartSection,
  ];

  return parts.filter(p => p.length > 0).join('\n\n') + '\n';
}

function renderFrontmatter(llmConfig: LlmConfigStatus, createdAt: string): string {
  const lines = [
    '---',
    'title: Wiki Founding Note',
    'type: welcome',
    `created: ${createdAt}`,
  ];
  // LLM configuration status, machine-readable only. Hidden in Obsidian
  // reading view by default. Keeps the body clean for the user while
  // still preserving a stable record of the install state at write time.
  lines.push(`llm_config_status: ${llmConfig.ok ? 'ok' : 'failed'}`);
  if (llmConfig.ok) {
    if (llmConfig.provider) lines.push(`llm_config_provider: ${llmConfig.provider}`);
    if (llmConfig.model) lines.push(`llm_config_model: ${llmConfig.model}`);
  } else if (llmConfig.error) {
    // Quote the error to be safe against YAML-special characters (':', '#', etc.).
    lines.push(`llm_config_error: "${llmConfig.error.replace(/"/g, '\\"')}"`);
  }
  lines.push('---');
  return lines.join('\n');
}

function renderVerifySection(llmConfig: LlmConfigStatus): string {
  if (llmConfig.ok) {
    return [
      '## How to verify the install',
      '',
      'If you can read this in your wiki language, the install is working.',
      '',
      'The LLM configuration itself is verified from **Settings → Karpathy LLM Wiki → LLM Provider → Test Connection** (look for ✅).',
    ].join('\n');
  }
  return [
    '## How to verify the install',
    '',
    'This note is in English because the LLM is not yet configured. To enable wiki generation:',
    '',
    '1. Open **Settings → Karpathy LLM Wiki → LLM Provider**.',
    '2. Pick a provider, enter the API key, select a model.',
    '3. Click **Test Connection** — it must show ✅ before proceeding.',
    '4. Click **Save Settings**, then run `Karpathy LLM Wiki: Recreate Wiki Welcome Note` from the command palette.',
  ].join('\n');
}

function renderHowToUseSection(): string {
  return [
    '## How to use this plugin',
    '',
    'Open the command palette with `Ctrl/Cmd + P` and search "Karpathy LLM Wiki". The first command below is the only one you need on day one.',
    '',
    '| Command | What it does |',
    '| --- | --- |',
    '| `Karpathy LLM Wiki: Ingest multiple files` | Pick N source notes; the plugin extracts entities / concepts / sources from each and writes wiki pages. **Day one — start here.** |',
    '| `Karpathy LLM Wiki: Ingest single source` | Same as above, for one file. |',
    '| `Karpathy LLM Wiki: Ingest from folder` | Ingests every file in a chosen folder (e.g. `inbox/2024/`). |',
    '| `Karpathy LLM Wiki: Query Wiki` | Opens the right-side chat panel for asking questions against the ingested content. |',
    '| `Karpathy LLM Wiki: Lint wiki` | Runs the Lint pipeline (dead links, orphans, duplicates). Use when the wiki has ~30+ pages. |',
    '| `Karpathy LLM Wiki: View Ingestion History` | Opens a panel listing what each previous Ingest call created/updated. |',
    '| `Karpathy LLM Wiki: Recreate Wiki Welcome Note` | Re-creates this note in the current wiki language. |',
    '',
    'The right-side Query panel can also be opened by the chat-bubble ribbon icon.',
  ].join('\n');
}

function renderStructureSection(): string {
  return [
    '## What the wiki structure means',
    '',
    'After you ingest a source note, the plugin writes a small set of pages into your `wiki/` folder. Knowing the three core types — and the optional Schema layer on top — is the single most useful piece of background for the day you start curating the wiki by hand.',
    '',
    '### The three core page types',
    '',
    '- **`entities/`** — Named things: people, organizations, projects, products, events, places. A single source note typically produces several entity pages. Each entity page holds aliases, a summary, the source notes it appears in (`mentions_in_source`), and links to related entities and concepts.',
    '- **`concepts/`** — Topics, methods, definitions, fields of study, recurring themes. "PPR", "cardiology", "schema-driven design" are all concepts. Concept pages link to other concept pages; entity pages link to concept pages.',
    '- **`sources/`** — One page per ingested source note, with the original content plus a `source_file` frontmatter field. Source pages are the provenance anchor — every entity / concept page lists the source pages that mention it, so a reader can drill from a topic back to the originating note.',
    '',
    '### The Schema layer (optional)',
    '',
    'You can enable Schema from **Settings → Karpathy LLM Wiki → Schema**. When enabled, the plugin maintains a `wiki/schema/` folder that encodes your wiki\'s vocabulary — the controlled list of tag categories, section templates, and entity/concept types.',
    '',
    'The schema lives in a single Obsidian-format page: [[wiki/schema/config]]. Open it to see the active vocabulary; the plugin rewrites this page whenever the vocabulary changes.',
    '',
    '- Ingest prompts are bound to this vocabulary, so the LLM picks tags and section headings from a fixed list rather than inventing free-form text.',
    '- When the LLM notices drift (e.g. a new concept not in the vocabulary), the suggestion appears in the Lint report modal — you accept / reject before it lands.',
    '- When the vocabulary changes, every existing page is rewritten to match (auto-backup to `.llm-wiki-backups/schema/`, rotation MAX_BACKUPS=3).',
    '',
    'Without Schema, the plugin still works — the three core types are always created. Schema adds structure that makes queries more reliable on a mature wiki.',
    '',
    '### The wikilink graph',
    '',
    'Every `[[wiki-link]]` between two pages is a relationship the LLM established at ingest time. The plugin uses this graph (not embeddings) for query retrieval — see the v1.23.0 release notes for the graph engine architecture. Practical takeaway: a well-curated wikilink graph is the wiki\'s "search index". You can add or edit `[[X]]` links by hand in any page, and the next query will pick them up.',
    '',
    '### The folder layout',
    '',
    'All wiki files live under `wiki/` (configurable in Settings → Wiki folder):',
    '',
    '```',
    'wiki/',
    '├── entities/    # Named things (people, orgs, projects)',
    '├── concepts/    # Topics, methods, definitions',
    '├── sources/     # One page per ingested note (provenance)',
    '├── schema/      # Optional vocabulary + section templates',
    '├── index.md     # Auto-generated graph index',
    '└── log.md       # Auto-generated activity log',
    '```',
  ].join('\n');
}

function renderQuickStartSection(): string {
  return [
    '## Quick start',
    '',
    '1. **Pick a few source notes to ingest.** Run `Karpathy LLM Wiki: Ingest multiple files` from the command palette. Tick the notes you want, then click **Add to queue**. The modal stays open so you can watch progress.',
    '2. **Wait for ingest to finish.** Each note takes 10–60 seconds (LLM extraction). You can keep working — completions appear as Notices. `View Ingestion History` lists every batch\'s result.',
    '3. **Try a query.** Open the right-side Query Wiki panel (chat-bubble ribbon icon) and ask something about your content.',
    '4. **Tune settings if needed.** Settings → Karpathy LLM Wiki: language, wiki folder, schema, tag vocabulary, auto-watch. Defaults are sensible for new vaults.',
    '',
    '> Full guide in the README: github.com/green-dalii/obsidian-llm-wiki',
  ].join('\n');
}